# Generated by Django 2.2 on 2023-03-23 17:15
from typing import List
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies: List[str] = []

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('address_id', models.IntegerField()),
                ('bandwidth', models.IntegerField(null=True)),
                ('customer_address_id', models.IntegerField()),
                ('decommission_date', models.DateTimeField(null=True)),
                ('description', models.TextField()),
                ('group_name', models.CharField(max_length=250, null=True)),
                ('hand_off_point', models.CharField(max_length=20, null=True)),
                ('install_date', models.DateTimeField()),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('reference_number', models.IntegerField()),
                ('reference', models.CharField(default='', max_length=100, null=True)),
                ('supplier_address_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'circuit',
                'ordering': ['reference_number'],
            },
        ),
        migrations.CreateModel(
            name='CircuitClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('name', models.CharField(max_length=250)),
                ('member_id', models.IntegerField()),
            ],
            options={
                'db_table': 'circuit_class',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('key', models.CharField(max_length=250)),
                ('required', models.BooleanField()),
            ],
            options={
                'db_table': 'property',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'property_type',
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='propertytype',
            index=models.Index(fields=['id'], name='property_type_id'),
        ),
        migrations.AddIndex(
            model_name='propertytype',
            index=models.Index(fields=['name'], name='property_type_name'),
        ),
        migrations.AddField(
            model_name='property',
            name='circuit_class',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='properties',
                to='circuit.CircuitClass',
            ),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='circuit.PropertyType'),
        ),
        migrations.AddIndex(
            model_name='circuitclass',
            index=models.Index(fields=['id'], name='circuit_class_id'),
        ),
        migrations.AddIndex(
            model_name='circuitclass',
            index=models.Index(fields=['name'], name='circuit_class_name'),
        ),
        migrations.AddIndex(
            model_name='circuitclass',
            index=models.Index(fields=['member_id'], name='circuit_class_member_id'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='circuit_class',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='circuits',
                to='circuit.CircuitClass',
            ),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['id'], name='property_id'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['key'], name='property_key'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['required'], name='property_required'),
        ),
        migrations.AddIndex(
            model_name='circuit',
            index=models.Index(fields=['id'], name='circuit_id'),
        ),
        migrations.AddIndex(
            model_name='circuit',
            index=models.Index(fields=['address_id'], name='circuit_address_id'),
        ),
        migrations.AddIndex(
            model_name='circuit',
            index=models.Index(fields=['customer_address_id'], name='circuit_customer_address_id'),
        ),
        migrations.AddIndex(
            model_name='circuit',
            index=models.Index(fields=['decommission_date'], name='circuit_decommission_date'),
        ),
        migrations.AddIndex(
            model_name='circuit',
            index=models.Index(fields=['description'], name='circuit_description'),
        ),
        migrations.AddIndex(
            model_name='circuit',
            index=models.Index(fields=['group_name'], name='circuit_group_name'),
        ),
        migrations.AddIndex(
            model_name='circuit',
            index=models.Index(fields=['install_date'], name='circuit_install_date'),
        ),
        migrations.AddIndex(
            model_name='circuit',
            index=models.Index(fields=['reference_number'], name='circuit_reference_number'),
        ),
        migrations.AddIndex(
            model_name='circuit',
            index=models.Index(fields=['reference'], name='circuit_reference'),
        ),
        migrations.AddIndex(
            model_name='circuit',
            index=models.Index(fields=['supplier_address_id'], name='circuit_supplier_address_id'),
        ),
    ]
