# Generated by Django 2.2 on 2023-03-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0002_triggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circuit',
            name='customer_address_id',
            field=models.IntegerField(null=True),
        ),
    ]
