# Generated by Django 2.2 on 2023-04-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0003_custoemr_address_optional'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='circuit',
            name='circuit_description',
        ),
    ]
