# Generated by Django 2.2 on 2023-04-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circuit', '0004_remove_circuit_description_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='circuit',
            name='circuit_supplier_address_id',
        ),
        migrations.RenameField(
            model_name='circuit',
            old_name='supplier_address_id',
            new_name='service_provider_address_id',
        ),
        migrations.AddIndex(
            model_name='circuit',
            index=models.Index(fields=['service_provider_address_id'], name='circuit_sp_address_id'),
        ),
    ]
